baseURL = "https://eru.sh"
languageCode = "zh-CN"
title = "Eru"
tags = ["eru", "container", "docker"]

theme = "kube"
description ="Another container orchestration platform"

pygmentsCodeFences = true
pygmentsStyle = "monokailight"

[params]
    RSSLink = "/index.xml"
    author = "CMGS"
    github = "projecteru2"
    twitter = "CMGS1988"
    email = "ilskdw@gmail.com"
    font = "Lato"

[[menu.main]]
    name = "Docs"
    weight = -100
    url = "https://book.eru.sh/"
